data/gimagereader.desktop.in

It's recommended to have Keywords in the desktop file as Unity, Gnome Shell etc. rely on them for proposing applications to users, see: https://wiki.gnome.org/Initiatives/GnomeGoals/DesktopFileKeywords

Add Keywords to desktop file as recommended

---

gtk/src/MainWindow.cc

The function prctl() is Linux specific, it's not available on all Unix Systems, especially not on *BSD. That makes gImageReader fail to build on kfreebsd. See https://buildd.debian.org/status/fetch.php?pkg=gimagereader&arch=kfreebsd-amd64&ver=3.0.1-1&stamp=1430084023 for reference.

prctl is Linux specific

---

gtk/src/MainWindow.cc

ARMEL's CPU default is too old to support std::exception_ptr. As Debian sill builds for ARMEL it fails to build without.

On ARMEL std::exception_ptr is missing - GTK+ part of the fix.

---

qt/src/MainWindow.cc

ARMEL's CPU default is too old to support std::exception_ptr. As Debian sill builds for ARMEL it fails to build without.

On ARMEL std::exception_ptr is missing - QT part of the fix.

---

gtk/src/OutputEditorHOCR.cc

We shouldn't clear the m_currentItem, because m_itemStore->erase triggers
selection change.
Fixes crash caused by an invalid iterator.
PS: Is there any code style guidelines for contributors for cases like `if(...) {`?

[GTK] OutputEditorHOCR: Fix removeCurrentItem

---

qt/src/OutputEditorHOCR.cc

Fixes crash after clicking on empty area below items.

[Qt] OutputEditorHOCR: Don't work with null item

---

gtk/src/Displayer.cc

Fixes crash after drag-and-dropping non-image files.

[Gtk] Displayer::setSources: Don't work with null m_currentSource

---

qt/src/Displayer.cc

Basically the same as #116 . Qt version, however, doesn't crash with unsupported formats, since they are filtered, but it will with corrupt images/PDFs.

[Qt] Displayer::setSources: Don't work with null m_currentSource

---

gtk/src/SubstitutionsManager.cc

Fixes false error message after loading a list that contains empty pairs.
It probably makes sense to set `keedEmpty` to `true` by default to match Qt's behavior.

[Gtk] SubstitutionsManager::openList: Keep empty lines in Utils::string_split

---

qt/src/Displayer.cc

We cannot use m_imageItem->sceneBoundingRect() since its pixmap
can currently be downscaled and therefore have slightly different
proportions.

[Qt] Displayer::getSceneBoundingRect: Fix size deviations

---

qt/src/Displayer.cc

Significantly improves quality of rotated images:

[Qt] Displayer::getImage: Use smooth pixmap transformation

---

gtk/src/OutputEditorText.cc
qt/src/OutputEditorText.cc

Hi,
here is the pull request. 
I added »« on both "sides" as both can mark opening and closing of quotes (see https://en.wikipedia.org/wiki/Guillemet).
Best,
Philip

Recognize guillemets as quote characters (fixes #177)

---

qt/src/hocr/OutputEditorHOCR.cc

textChanged wasn't correctly triggering validateChanges.
Seems to have resolved some long hangs on ignoring words/adding words to dictionary. Haven't looked closely enough yet to be certain of why, but the typo's clear enough.

[Qt] Fix bug in HOCRAttributeEditor constructor

---

qt/src/hocr/HOCRPdfExporter.cc

when choose QT ui, Compile complain that Qurl is a imcomplete type.

fix incomplete type 'QUrl' compile err in ubuntu 16.04

---

qt/src/hocr/HOCRDocument.cc

Fixes #250.
`QModelIndex.child()` is implemented by way of `QAbstractItemModel`'s (i.e., `HOCRDocument`'s) `index()`, which retrieves children by index (row) from their parent's `m_childItems`. Therefore, calls to `child()` will reflect any deletions already made (since `deleteItem()` removes the item to delete from that vector).
The indexing here was as such incorrect and would try to retrieve items after those actually selected, causing bad behavior and, if reaching beyond the end of the child list, a segfault (on `->takeChildren`) and crash. (Yes, the Q_ASSERT here will fail—if compiled in, which tripped me up at first because I neglected that the CMake list defaults to Q_NO_DEBUG.)

[Qt] fix n-ary merge crash

---

gtk/data/gimagereader.gresource.xml

gdk-pixbuf-pixdata is deprecated and GResource files can embed .png files directly without conversion

[gtk] remove unrequired pixdata conversions

---

qt/src/hocr/HOCRDocument.cc
qt/src/hocr/HOCRDocument.hh
qt/src/hocr/OutputEditorHOCR.cc

Added this as I couldn't live without it anymore. (With merge and swap, any reordering is now technically possible, if not necessarily convenient.) Selecting a contiguous block of words, textlines, or paragraphs and then choosing "Split" from the context menu creates a new sibling adjacent to the parent and moves items in the block there.
Also fixes a bug in which removeItem did not correctly recompute ancestor bounding boxes.
I looked into extending the remove option to multiple items as well. Unfortunately, this resulted in irregular segfaults _after_ the return from showTreeWidgetContextMenu, and as I have never been able to get the crash backtrace to work I'm not sure what might be causing them.

[Qt] Add option to split textlines, paragraphs, and text blocks in HOCR editor

---

gtk/src/TessdataManager.cc
qt/src/TessdataManager.cc

The error message displayed when gImageReader cannot connect to `org.freedesktop.PackageKit.Modify` on the session bus makes it sound like PackageKit is missing from the system, when in reality the `.Modify` session service is provided by applications like Gnome Software, not by PackageKit itself.
This change updates the message to be more explicit about what exactly is missing, with the new text (identical in the Qt and Gtk sources) reading:
> A session connection to the PackageKit backend is required for managing
> system-wide tesseract language packs, but it was not found. This service is
> usually provided by a software-management application such as Gnome Software.
> Please install software which provides the necessary PackageKit interface,
> use other system package management …

More explicit PackageKit error message

---

qt/src/Utils.cc

Qt5 guarantees that standard paths aren't empty, but not that they actually exist.
Most of this function's callers could already cope, but the crash handler tried to dump unsaved work in the returned location, which would totally fail.

[Qt] don't allow Utils::documentsFolder() to supply nonexistent dirs

---

qt/src/hocr/HOCRDocument.cc
qt/src/hocr/OutputEditorHOCR.cc

When creating a manually added hOCR item, if an attribute is propagatable to the item's class and all of the item's relatives agree on its value, apply the consensus value to the new item as well. Very minor QoL improvement.

[Qt] [hOCR] Propagate attributes down to manually added items 

---

qt/src/hocr/HOCRDocument.cc

This leads to handling contractions, hyphenated words, and acronyms/initialisms properly for the purposes of ignoring, adding, and suggesting.

[Qt] [hOCR] Correctly trim some words containing non-word characters

---

qt/src/hocr/OutputEditorHOCR.cc

Makes adding consistent with the rest of the actions that alter the tree. (In particular, it's now possible to add an item, select another item, and immediately swap them, where before the context menu would behave as though only the other element was selected.)

[Qt] [hOCR] Improve selection behavior after adding elements

---

qt/src/hocr/HOCRDocument.cc

The 'non-word' character class doesn't catch them since they're numbers. This isn't pretty, but I run into it a lot.

[Qt] [hOCR] Correctly trim words followed by superscript numbers

---

qt/data/PdfExportDialog.ui
qt/src/hocr/HOCRPdfExporter.cc
qt/src/hocr/HOCRPdfExporter.hh

Resolves #350.
The logic calculating output sizes coped poorly with image sources, since their "resolution" is actually the (percentage) scale factor used for recognizing. gIR would go ahead and interpret it as a physical ratio during export to PDF, leading to blowups in reported physical sizes, in image dimensions, and in file sizes if the user chose an accurate resolution. (For example, a a 7"×10" document scanned at 300 DPI into a 2100×3000 image file and recognized at 100% would, if exported at 300 DPI, result in a 21"×30" document containing a 6300×9000 image, for a serious inflation of the filesize.) It was possible to adjust the image dimensions by accounting for this behavior during the export, but not the physical size.
This adds an 'image source DPI' setting to the PDF export …

[Qt] [hOCR] Add option to specify DPI of image sources when exporting to PDF

---

qt/src/hocr/HOCRDocument.cc
qt/src/hocr/HOCRDocument.hh
qt/src/hocr/OutputEditorHOCR.cc

Resolves #362.
Changes `HOCRDocument` API slightly; `checkItemSpelling` is now public (taking an index) and should be used both for checking validity and (optionally) requesting suggestions.

[Qt] [hOCR] Rework spellcheck to handle unspaced dashes

---

data/gimagereader.appdata.xml.in

Each paragraphs and list items must be tagged, otherwise they are treated as English by appstream-generator.
This fixes the following error detected by `appstreamcli validate gimagereader-gtk.appdata.xml`:
```
E - gimagereader-gtk.appdata.xml:gimagereader-gtk.desktop:38
The 'description' tag should not be localized in upstream metadata. Localize the 
individual paragraphs instead.
```

Fix translation of list items in appdata

---

data/gimagereader.appdata.xml.in
data/gimagereader.desktop.in

I would like to enhance the AppData file.
This is related to submitting my flatpak package to the Flathub repository.
https://github.com/manisandro/gImageReader/issues/396
https://github.com/flathub/flathub/pull/810
You should also consider changing [application id](https://github.com/scx/flathub/blob/030990011b8622d86a478a3314c33592b2539aae/gimagereader.appdata.xml.in#L4), as well as renaming AppData, [desktop](https://github.com/scx/flathub/blob/030990011b8622d86a478a3314c33592b2539aae/gimagereader.appdata.xml.in#L61) and icon file.
https://github.com/flathub/flathub/wiki/AppData-Guidelines#id
Although It is not required, it is highly recommended.
See also:
https://github.com/flathub/flathub/wiki/AppData-Guidelines
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#ta …

Enhance AppData file

---

qt/src/Recognizer.cc
qt/src/Recognizer.hh

In Tesseract 5.0, TessBaseAPI class became non-copyable and gImageReader's initTesseract() fails to compile.
With this patch TessBaseAPI instance is handled by smart pointer.
This patch still keeps it compatible with Tesseract 4.0.

Fix FTBFS with Tesseract 5.0-alpha

---

qt/src/Config.cc

With Tesseract master now we have to include strngs.h explicitly to use STRING class.

Fix FTBFS with Tesseract 5-alpha

---

data/gimagereader.appdata.xml.in

The two interface uses the same gettext package name as defined here:
https://github.com/manisandro/gImageReader/blob/master/CMakeLists.txt#L48

Fix gettext package name

---

qt/src/main.cc

Qt toolbar icons are displayed too small on 4K display.
This PR makes its appearance better.
Before:
After:

Better HiDPI support

---

qt/src/Recognizer.cc

New Adaptive Otsu thresholding method is available in Tesseract 5.0.0 beta.
(See http://www.leptonica.org/binarization.html)
It makes better recognition result.

Apply adaptive Otsu thresholding instead of normal Otsu.

---

qt/src/main.cc

I made PR to fix HiDPI scaling https://github.com/manisandro/gImageReader/pull/528 and the PR was approved.
But the fix was reverted in fee875a75e62f2dc2fb37c56633f5a0487556662.
Qt6 doesn't need Qt::AA_EnableHighDpiScaling flag but Qt5 still needs it.
I make PR again with Qt_VERSION_CHECK.

Fix HiDPI scaling for Qt5 again

---

.gitignore
qt/src/DisplayRenderer.cc
qt/src/SourceManager.cc

(Newer versions of poppler fix the problem, but aren't available
on Debian 11.)
(cherry picked from commit a8bd81e2703eb335e020bd5166a39eb103b7678a)

Clean up remaining warnings.

---

qt/src/scanner/ScannerTwain.cc
qt/src/scanner/ScannerTwain.hh

In only Windows NativeEventFilter is used.
QAbstractNativeEventFilter interface has changed in Qt6.

Fix FTBFS in Windows with Qt6.

---

gtk/src/scanner/ScannerSane.cc
qt/src/scanner/ScannerSane.cc

An issue with distorted scan result was encountered for f+ imaging M60ade MFP.
$ sane-find-scanner -q
found USB scanner (vendor=0x043d [f+ imaging], product=0x0382 [f+ imaging M60ade]) at libusb:002:020
Debugging revealed following messages:
[...]
[New Thread 0x7fffaaffd640 (LWP 15083)]
Unable to set Color mode, please file a bug
Unable to set Color mode, please file a bug
Unable to set Gray mode, please file a bug
[Thread 0x7fffaaffd640 (LWP 15083) exited]
[Thread 0x7fffabfff640 (LWP 15081) exited]
while 'strings /usr/local/printer/unix_scan_drivers/lib/sane/libsane-mfp_nscan.so.1' showed custom constants:
[...]
1-bit Black & White
8-bit Grayscale
24-bit Color
[...]

Add custom scan modes seen in f+ imaging (Lexmark) proprietary driver

---

data/gimagereader.appdata.xml.in

- add developer name (can be shown in https://flathub.org/apps/details/io.github.manisandro.gImageReader)
- set `Translate` link to the Weblate page rather than the ambiguous `README.md`

improve appstream metadata

---

gtk/src/hocr/HOCRDocument.cc
gtk/src/hocr/OutputEditorHOCR.cc
qt/src/hocr/HOCRDocument.cc
qt/src/hocr/OutputEditorHOCR.cc

cf. https://github.com/kba/hocrjs/issues/68:
> The problem is the `res` property which is not part of the hOCR spec. I think this should be [`scan_res`](https://kba.github.io/hocr-spec/1.2/#scan_res), i.e. in https://github.com/manisandro/gImageReader/blob/8a046ec7bf64e996fbc81187306334fbd11873c9/qt/src/hocr/OutputEditorHOCR.cc#L268:
> 
> ```diff
> - 	attrs["res"] = QString::number(pageInfos.resolution);
> +	attrs["scan_res"] = QString::number(pageInfos.resolution);
> ```
ht @khashashin

hOCR editor: use "scan_res" instead of "res"

---

data/gimagereader.appdata.xml.in

It doesn't exist in the [specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots) any more and it [prevents](https://buildbot.flathub.org/#/builders/19/builds/14658) the program from being built on flathub

Remove deprecated <comment> tag in the appstream metadata

---

data/gimagereader.appdata.xml.in

- Use desktop-application as component type
- Add vcs-browser URL to show the source code repository
- Update oars rating version to 1.1
More information: https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/

appdata: Fix appdata papercuts

---

qt/src/Displayer.cc
qt/src/RecognitionMenu.cc

Fix two memory management issues:
- Add missing deletion of m_imageItem in Displayer::setSources
- Set proper parent for PSM menu to ensure proper cleanup
These changes prevent memory leaks and ensure proper resource cleanup when the application exits or when components are destroyed.

fix: Fix memory leaks in Displayer and RecognitionMenu

---

qt/src/FileTreeModel.cc
qt/src/FileTreeModel.hh

1. class member 'FileTreeModel::OutputFileRole' is never used.
2. Local variable 'pos' shadows outer varibale.
3. Variable 'tempPath' is assigned a value that is never used.

chore: remove some variable that never used.

---

qt/src/hocr/HOCRDocument.cc
qt/src/hocr/HOCRDocument.hh

1. Variable 'child' can be declared as pointer to const.
2. Function 'moveItem' argument 3 names different: declaration 'row' definition 'newRow'.
3. Function 'swapItems' argument 2 names different: declaration 'startRow' definition 'firstRow'.
4. Function 'insertChild' argument 2 names different: declaration 'index' definition 'i'.

chore: some function argument name different.
