gtk/src/Config.cc
po/LINGUAS
po/zh_HK.po
po/zh_TW.po
qt/src/Config.cc

Translations for zh_TW and zh_HK have been added.  There is also a fix for auto-detection of Traditional Chinese in Config.cc.

Add Traditional Chinese translations

---

gtk/data/gimagereader.ui
po/pt_BR.po
qt/data/AboutDialog.ui

Inserting entry in the credits

Inserting in the credits for translation

---

po/uk.po

Fix a couple of existing strings and translate most of the untranslated ones.

Correct and extend Ukrainian translation

---

po/fr.po

Small corrections for fr translation

---

po/LINGUAS
po/zh_CN.po
po/zh_HK.po
po/zh_TW.po

In addition to updating existing Traditional Chinese translations, Simplified Chinese translation has been added for completeness.

Update Chinese translations

---

CMakeLists.txt
data/gimagereader.appdata.xml.in

Hi,
I updated the appstream metadata the current format, following:
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
Best,
Philip

Update appstream meatadata to current format

---

qt/data/PdfExportDialog.ui
qt/src/OutputEditorHOCR.cc

Feature: open output PDF with default application

---

gtk/src/DisplayRenderer.cc
gtk/src/DjVuDocument.cc
gtk/src/DjVuDocument.hh
gtk/src/OutputEditorHOCR.cc
gtk/src/Recognizer.cc
qt/data/PdfExportDialog.ui
qt/src/DisplayRenderer.cc
qt/src/DisplayRenderer.hh
qt/src/Displayer.cc
qt/src/DjVuDocument.cc
qt/src/DjVuDocument.hh
qt/src/FileDialogs.cc
qt/src/OutputEditorHOCR.cc
qt/src/OutputEditorHOCR.hh
qt/src/OutputEditorText.cc
qt/src/Recognizer.cc
qt/src/Utils.cc

Feature: Save encrypted pdf

---

qt/src/SourceManager.cc
qt/src/SourceManager.hh

Hello,
here is simple check for text layer in PDF. Probably it should be extended.

Add check for text layer in PDF file

---

qt/data/PdfExportDialog.ui
qt/src/SourceManager.cc
qt/src/SourceManager.hh
qt/src/hocr/HOCRPdfExporter.cc
qt/src/hocr/HOCRPdfExporter.hh

It's PR about extracting additional info from PDF.

Extract additional info about PDF

---

qt/src/Recognizer.cc
qt/src/hocr/OutputEditorHOCR.cc

qSort is deprecated in Qt (you can see it in qSort definition). I replaced it with std::sort as Qt recommends.

Replace qSort by std::sort.

---

qt/src/scanner/ScannerSane.cc
qt/src/scanner/ScannerSane.hh

A little bit improved error messages for scannerSane.
Probably in implementation should be used Optional instead of defaultMessage.

[Qt] Improve error messages

---

qt/src/hocr/HOCRPdfExporter.cc

Hello @manisandro .
Here is small fix for PDF documents without password.

[Qt] Fix PDF rights for documents without password

---

qt/src/hocr/HOCRDocument.cc

See https://github.com/manisandro/gImageReader/issues/226#issuecomment-410065373. (I've fiddled with the history a bit in order to break out #367.)

[Qt] [hOCR] Check spelling properly for hyphenated words broken across lines

---

NEWS
data/manual.html.in
gtk/data/org.gnome.gimagereader.gschema.xml
gtk/src/OutputEditorText.cc
gtk/src/hocr/HOCRDocument.cc
gtk/src/hocr/HOCRDocument.hh
gtk/src/hocr/OutputEditorHOCR.cc
gtk/src/hocr/OutputEditorHOCR.hh
packaging/win32/installer.nsi
qt/src/OutputEditorText.cc
qt/src/OutputTextEdit.cc
qt/src/hocr/HOCRDocument.hh
qt/src/hocr/OutputEditorHOCR.cc

They were found using codespell.
Signed-off-by: Stefan Weil <sw@weilnetz.de>

Fix some typos

---

po/de.po

Updated de.po

---

README.md
data/gimagereader.appdata.xml.in

1. Updated readme.md to include link to Desktop entry/icon
2. Updated English
3. Added Hungarian (magyar)
4. Is it possible to update the appdata file to look like https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/mmex.desktop? It might be easier to maintain.
5. Hopefully now there will be a comment `Optical character recognition using Tesseract` for the program:
* ![image](https://github.com/manisandro/gImageReader/assets/17465872/a9d8bb5a-132c-4e42-98cb-a2b8cf8933d1)
* ![image](https://github.com/manisandro/gImageReader/assets/17465872/356295fd-7516-4b06-8c34-0c0efad968bb)
Thank you

readme and desktop entry updates

---

README.md

Fix Arch links

---

qt/src/scanner/ScannerSane.cc

An error message appears when scanning again
scanner - Mustek Systems, Inc. ScanExpress 1200 CU Plus

fix re-scan

---

.gitignore

Chore: Ignore temporary files generated by the QtCreator build.

---

qt/src/Acquirer.cc
qt/src/Displayer.cc

1. Some array variable can be declared as const array.
2. Add null pointer check logic for pointer variables.

fix: Add null pointer check logic for pointer variables.

---

qt/src/hocr/HOCRBatchExportDialog.cc
qt/src/hocr/HOCRDocument.cc
qt/src/hocr/HOCRDocument.hh
qt/src/hocr/HOCRProofReadWidget.cc

1. Some variable can be declared as pointer to const.
2. The scope of the variable 'targetLine' can be reduced.
3. Local variable 'bottomLeft' shadows outer variable

chore: Improve code robustness and maintainability.

---

gtk/src/hocr/HOCRPdfExporter.cc

As the title says: fixes the build error reported in #723

gtk: Fix conversion to c-string (fixes #723)
